name: CI/CD for Restaurant Service

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -f RestaurantManagementService/Dockerfile -t vidura12/restaurant-service:latest RestaurantManagementService

      - name: Push Docker image to Docker Hub
        run: docker push vidura12/restaurant-service:latest

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set KUBECONFIG from base64 encoded secret
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_B64 }}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Deploy to Kubernetes
        run: kubectl apply -f RestaurantManagementService/restaurant-service.yaml
