name: CI for Restaurant Service

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the current repository (Restaurant service code)
      - name: Checkout repository
        uses: actions/checkout@v3

      # (Optional) Step 2: Clone Kubernetes Config Repository (can be removed if not needed)
      - name: Clone Kubernetes Config Repository
        uses: actions/checkout@v3
        with:
          repository: 'Deliveroo-System/ds-project-kubernetes'
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main
          path: kubernetes

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Step 4: Build the Docker image
      - name: Build Docker image
        run: docker build -f RestaurantManagementService/Dockerfile -t vidura12/restaurant-service:latest RestaurantManagementService

      # Step 5: Push the Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: docker push vidura12/restaurant-service:latest
