name: Docker CI/CD - Restaurant Service

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Step 3: Build and push Docker image
      - name: Build and push restaurant-service
        run: |
          docker build -t vidura12/ds-project:restaurant-service .
          docker push vidura12/ds-project:restaurant-service

  deploy-to-kubernetes:
    runs-on: ubuntu-latest
    needs: build-and-push  # Wait for build-and-push job to complete
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Checkout Kubernetes manifests
      - name: Checkout Kubernetes manifests
        uses: actions/checkout@v3
        with:
          repository: vidura12/ds-project-kubernetes
          path: kubernetes

      # Step 3: Set up kubectl
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      # Step 4: Deploy to Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f kubernetes/restaurant-service.yaml